### ISSUE TITLE
beautiful! 

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/week-3-MEIA#16]
Really love the colour scheme, presentation and layout of your site - it's so well thought out and very easy to follow. Great job!

**Comment by Coletterbox** [comment]
Yep, I was thinking that! The layout is clean, and the background colour is well-chosen; it perfectly balances out the fact that half the tube lines are garish crayon colours.

**Comment by andy-mc-donald** [comment]
Thanks guys!
