### ISSUE TITLE
spelling mistake :0

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/week-3-MEIA#20]
<img width="429" alt="Screenshot 2019-07-19 at 10 20 01" src="https://user-images.githubusercontent.com/36238916/61524698-e46b1d80-aa0e-11e9-9587-1fa870dd9387.png">

Trainspiration is spelt with an "i" in your title but without on the main page - think it's just been forgotten? Easy to do!

**Comment by sarahyjja** [comment]
Done 👍
