### ISSUE TITLE
meme load time slow

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/week-3-MEIA#27]
<img width="1440" alt="Screenshot 2019-07-19 at 10 26 47" src="https://user-images.githubusercontent.com/36238916/61525251-ea153300-aa0f-11e9-9bbf-ed077550c454.png">
<img width="1440" alt="Screenshot 2019-07-19 at 10 25 11" src="https://user-images.githubusercontent.com/36238916/61525268-eed9e700-aa0f-11e9-8b42-31d756a6bfbb.png">

Don't you just hate slow load times?! We've had problems with our APIs being super slow too - not great for the user but know there's not much to be done about it.
This is something I've promised myself I'll look into more, but had a quick google search now and this article seems fairly useful https://medium.com/front-end-weekly/how-to-optimize-image-loading-on-your-website-855020fb41ae
Perhaps not something to fix now but useful in future projects?

**Comment by crianonim** [comment]
Thank you for your suggestion, we could put some placeholder picture.
