### ISSUE TITLE
TESTS!!!!!!!!

### ISSUE THREAD

**Issue by Dalmano** [fac-17/week-3-MEIA#36]
I couldn't be happier! Very impressed you wrote tests...AND you did so for *both* APIs

**Comment by reubengt** [comment]
Was a hard one to write tests on, since we couldn't write tests on the API requests themselves. Ended up making helper functions that abstract some of the dom work/adding css classes, and testing their input and output.
@Dalmano

**Comment by reubengt** [comment]
Thanks for the compliment!
