### ISSUE TITLE
Title?

### ISSUE THREAD

**Issue by Dalmano** [fac-17/week-3-MEIA#39]
Think about chromevox, it won't read 'Trainspiration' until it reaches the second section. To make it clear, maybe add a title, unless that's not the vibe you're going for

**Comment by reubengt** [comment]
I think we were going for a dashboard look, similar to the macOS dashboard. ChromeVox does read the page title first, and then immediately reads "Good Morning, its 9:09 am", so trainspiration is the first thing the user hears. just didnt want an actual title on the page :D
